# Generated by Django 3.1.7 on 2021-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
