# Generated by Django 3.1.7 on 2021-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0002_auto_20210319_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='buy',
            constraint=models.CheckConstraint(check=models.Q(quantity__gte=0), name='buy_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(check=models.Q(money__gte=0), name='money_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(quantity__gte=0), name='product_quantity_gte_0'),
        ),
    ]
