# Generated by Django 3.1.7 on 2021-03-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0003_auto_20210319_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ['-buy_at', 'product']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='returnproduct',
            options={'ordering': ['-return_product_at']},
        ),
    ]
