# Generated by Django 3.1.7 on 2021-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0004_auto_20210322_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buy_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='return_product_at',
            field=models.DateTimeField(),
        ),
    ]
