# Generated by Django 3.1.7 on 2021-03-23 19:14

from django.db import migrations


def some_forward_action(apps, schema_editor):
    Team = apps.get_model('buyline', 'Product')
    Team.objects.create(
        name='Game chair',
        description='Chair, you can sit on it',
        price=2000,
        quantity=20
    )
    Team.objects.create(
        name='Keyboard',
        description='For interaction with pc',
        price=800,
        quantity=15
    )

class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0005_auto_20210322_1436'),
    ]

    operations = [
        migrations.RunPython(some_forward_action, lambda x, y: None)
    ]
