# Generated by Django 3.1.7 on 2021-03-30 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyline', '0006_auto_20210323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_product', to='buyline.product'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_buy', to='buyline.buy'),
        ),
    ]
